# Generated by Django 4.0.4 on 2022-04-26 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_remove_bookshelf_title_bookshelf_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookshelf',
            name='title',
            field=models.ManyToManyField(related_name='on_shelf', to='main_app.book'),
        ),
    ]
