# Generated by Django 4.0.4 on 2022-04-26 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_rename_title_bookshelf_titles'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookshelf',
            old_name='titles',
            new_name='title',
        ),
    ]
