# Generated by Django 4.0.4 on 2022-04-27 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_rename_titles_bookshelf_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookshelf',
            old_name='title',
            new_name='shelved',
        ),
    ]
