# Generated by Django 4.0.4 on 2022-04-25 19:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0004_reviews_remove_bookshelf_star_rating_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(editable=False)),
                ('subject', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('star_rating', models.PositiveSmallIntegerField(choices=[(0, '0 stars'), (1, '1 star'), (2, '2 stars'), (3, '3 stars'), (4, '4 stars'), (5, '5 stars')], help_text='How would you rate this book?')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.book')),
            ],
        ),
        migrations.DeleteModel(
            name='Reviews',
        ),
        migrations.RenameField(
            model_name='bookshelf',
            old_name='user',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='bookshelf',
            old_name='book',
            new_name='title',
        ),
    ]
