# Generated by Django 4.0.4 on 2022-04-26 01:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0005_review_delete_reviews_rename_user_bookshelf_owner_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookshelf',
            options={'verbose_name': 'bookshelf', 'verbose_name_plural': 'bookshelves'},
        ),
        migrations.RemoveField(
            model_name='bookshelf',
            name='id',
        ),
        migrations.AlterField(
            model_name='bookshelf',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
