# Generated by Django 4.0.4 on 2022-04-26 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_bookshelf_options_remove_bookshelf_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookshelf',
            name='title',
        ),
        migrations.AddField(
            model_name='bookshelf',
            name='title',
            field=models.ManyToManyField(to='main_app.book'),
        ),
    ]
