# Generated by Django 4.0.4 on 2022-04-27 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_alter_review_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='title',
            new_name='book_reviewed',
        ),
        migrations.AddField(
            model_name='review',
            name='have_finished',
            field=models.BooleanField(default=False),
        ),
    ]
