# Generated by Django 4.0.4 on 2022-04-28 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_alter_review_star_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookshelf',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='bookshelf',
            name='shelved',
        ),
        migrations.RemoveField(
            model_name='review',
            name='book_reviewed',
        ),
        migrations.RemoveField(
            model_name='review',
            name='owner',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='Bookshelf',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
